version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_challenge
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
